---
- hosts: all
  become: yes 

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: Get software for apt repository management
      apt:
        state: present
        name:
          - python3-apt
          - python3-pycurl

    - name: "Install Apache, MySQL, PHP and other dependencies for Drupal"
      apt:
        state: present
        name:
          - acl
          - git
          - curl
          - unzip
          - sendmail
          - apache2
          - php7.3
          - php7.3-common
          - php7.3-cli
          - php7.3-dev
          - php7.3-gd
          - php7.3-curl
          - php7.3-json
          - php7.3-opcache
          - php7.3-xml
          - php7.3-mbstring
          - php7.3-pdo
          - php7.3-mysql
          - php-apcu
          - libpcre3-dev
          - libapache2-mod-php7.3
          - python3-mysqldb # need this?
          - python-pymysql
          - python3-pymysql # need both?
          - mariadb-server

    # Installing on Debian 10 
    # Need to configure firewall and ports 
    # - name: "Configure firewall to OFF for now (CHANGE FOR PRODUCTION~!)"
    #   service: name=ufw state=stopped

    - name: "Start Apache, MySQL and PHP"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    - name: Enable Apache rewrite module (required for Drupal)
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: Add Apache virtualhost for Drupal
      template:
        src: "templates/drupal.test.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: Enable the Drupal site
      command:
        a2ensite {{ domain }}.test
        creates=/etc/apache2/sites-enabled/{{ domain }}.test.conf
      notify: restart apache

    - name: Disable the default site
      command:
        a2dissite 000-default
        removes=/etc/apache2/sites-enabled/000-default.conf
      notify: restart apache

    # Example in action: lineinfile module
    - name: Adjust OpCache memory setting.
      lineinfile:
        dest: "/etc/php/7.3/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache

  # MariaDB Ansible Galaxy Plugin
  roles:
    - role: mahdi22.mariadb_install
      become: yes
      vars:
        mariadb_version: "10.5"
        deny_remote_connections: true
        mysql_root_password: "azerty"
        create_database: true
        database: database_test
        create_db_user: true
        db_user_name: user_database
        db_user_password: password
