# base/tasks/main.yml
---
- name: Get software for apt repository management
  apt:
    state: present
    name:
      - python3-apt
      - python3-pycurl
# Custom PHP8 because Debian is on PHP 7.3 or 7.4
- name: Get dependencies for installing PHP 8 from Sury
  apt:
    state: present
    name:
      - lsb-release
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - gnupg2
# Custom PHP8 because Debian is on PHP 7.3 or 7.4
- name: add Sury PHP apt-key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
# Custom PHP8 because Debian is on PHP 7.3 or 7.4
- name: add Sury PHP apt repository
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ {{ deb_release }} main'
    state: present
    filename: sury-php
    update_cache: yes

- name: "Install Apache, MySQL, PHP and other dependencies for Drupal"
  apt:
    state: present
    name:
      - acl
      - git
      - curl
      - unzip
      - sendmail
      - apache2
      - php{{ php_v }}
      - php{{ php_v }}-cli
      - php{{ php_v }}-common
      - php{{ php_v }}-dev
      - php{{ php_v }}-opcache
      - php{{ php_v }}-pdo
      - php{{ php_v }}-xml
      - php{{ php_v }}-gd
      - php{{ php_v }}-curl
      - php{{ php_v }}-mbstring
      - php{{ php_v }}-mysql
      - php{{ php_v }}-zip
      - libapache2-mod-php{{ php_v }}
      - php-apcu
      - libpcre3-dev
      - python3-mysqldb # need this?
#     - python-pymysql # not available on Ubuntu 22
      - python3-pymysql # need both?
      - mariadb-server
      - neofetch

- name: "Start Apache, MySQL and PHP"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2
    - mysql

- name: Enable Apache rewrite module (required for Drupal)
  apache2_module: name=rewrite state=present
  notify: restart apache

- name: Add Apache virtualhost for Drupal
  template:
    src: "templates/drupal.test.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Enable the Drupal site
  command:
    a2ensite {{ domain }}.test
    creates=/etc/apache2/sites-enabled/{{ domain }}.test.conf
  notify: restart apache

- name: Disable the default site
  command:
    a2dissite 000-default
    removes=/etc/apache2/sites-enabled/000-default.conf
  notify: restart apache

- name: Create Drupal site directory
  file:
    path: /var/www/weberpl_org
    owner: www-data
    group: www-data
    mode: 0775
    state: directory
  notify: restart apache

# Example in action: lineinfile module
- name: Adjust OpCache memory setting.
  lineinfile:
    dest: "/etc/php/{{ php_v }}/apache2/conf.d/10-opcache.ini"
    regexp: "^opcache.memory_consumption"
    line: "opcache.memory_consumption = 96"
    state: present
  notify: restart apache

# Community MySQL Ansible Galaxy Plugin
- name: Create database user 'dbadmin' and password 'ohniner09' with all privs
  community.mysql.mysql_user:
    name: dbadmin
    password: ohniner09
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    state: present

- name: Create new databases with names 'foo' and 'bar'
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: dbadmin
    login_password: ohniner09
    name:
      - foo
      - bar
      - weberpl_org_{{ sub }}
    state: present
...
